/**
 * @file i2c.h
 * @author Jacob Meyer
 * @brief This file contains the implementation of I2C functions for the LSM303DLHC.
 *
 * Specifically, it retrieves the X/Y/Z readings from the linear accelerometer
 * and returns them in the form of a struct "AccelData." It also provides a boolean
 * check for whether the data can be interpreted as the device being in a level
 * orientation within a specified tolerance.
 */

#ifndef SRC_I2C_H_
#define SRC_I2C_H_

#include "stm32f1xx_hal.h"

#define LSM303DLHC_ADDRESS_ACCEL (0x19 << 1) // subaddress for linear accelerometer
#define LSM303DLHC_OUT_X_L_A (0x2C) // register address for X-axis low byte
#define LSM303DLHC_DATA_MAX_BYTES (6) // 2 bytes of data per axis (X_L, X_H, Y_L, Y_H, Z_L, Z_H)
#define LSM303DLHC_FLAG_AUTO_INCREMENT (0x80) // OR with subaddress to signal that the data register should auto-increment
#define LSM303DLHC_CTRL_REG1_A (0x20) // data rate selection, low-power mode, and X/Y/Z axis-enable

/**
 * @brief Specifies the minimum threshold of axes readings before accepting that the device is level.
 *
 * It is used in the is_level function to return a boolean value (0 or 1) accordingly.
 */
static const int16_t LEVEL_THRESHOLD = 0x400;

/**
 * @brief A global variable created generated by the .ioc file for handling the I2C peripheral.
 */
extern I2C_HandleTypeDef hi2c1;


/**
 * @struct AccelData
 * @brief Structure to hold accelerometer data.
 *
 * Contains the raw X, Y, and Z axis readings.
 */
typedef struct
{
	int16_t x;
	int16_t y;
	int16_t z;
} AccelData;

/**
 * @brief Initializes the LSM303DLHC linear accelerator control register.
 *
 * It sets the data rate to 100Hz, disables low-power mode, and enables each of
 * the X/Y/Z axes for data retrieval.
 *
 * @param none
 * @return HAL_OK if initialization is successful, HAL_ERROR otherwise.
 */
HAL_StatusTypeDef accel_init();

/**
 * @brief Reads and returns the data in all 3 accelerometer axes.
 *
 * It takes advantage of the LSM303DLHC register auto-increment feature to
 * read the 6 bytes of data (X_High, X_Low, Y_High, etc) in a single I2C frame.
 *
 * @param none
 * @return AccelData struct populated with raw X, Y, and Z axis readings.
 */
AccelData read_accelerometer_data();

/**
 * @brief Checks if both the X and Y axis data are within the level tolerance.
 *
 * @param none
 * @return 1 if within tolerance, 0 otherwise.
 */
uint8_t is_level(AccelData accel_values);

#endif /* SRC_I2C_H_ */
