BUILD_MACHINE := $(shell whoami)@$(shell hostname)
BUILD_DATE := $(shell date -u +"%d/%m/%Y, %H:%M")

version := $(subst -, ,$(shell git describe --long --dirty --tags))
COMMIT := $(strip $(word 3, $(version)))
COMMITS_PAST := $(strip $(word 2, $(version)))
DIRTY := $(strip $(word 4, $(version)))

ifneq ($(COMMITS_PAST), 0)
	BUILD_INFO_COMMITS := "."$(COMMITS_PAST)
endif

ifneq ($(DIRTY),)
	BUILD_INFO_DIRTY :="+"
endif

VERSION_TAG :=$(strip $(word 1, $(version)))
BUILD_INFO := $(COMMIT)$(BUILD_INFO_COMMITS)$(BUILD_INFO_DIRTY)

$(info Build Time: $(BUILD_DATE))
$(info Build Version: $(VERSION_TAG))
$(info Build Info: $(BUILD_INFO))

GEN_OPTS__FLAG += --define=VERSION_TAG="\"$(VERSION_TAG)\"" \
               --define=VERSION_BUILD_INFO="\"$(BUILD_INFO)\""\
               --define=VERSION_BUILD_MACHINE="\"$(BUILD_MACHINE)\""\
               --define=VERSION_BUILD_DATE="\"$(BUILD_DATE)\""
